{
    "Service": "/samplemdk/Services/mobileappazeem.service",
    "DefiningRequests": [{
            "Name": "Customers",
            "Query": "Customers"
        },
        {
            "Name": "ProductCategories",
            "Query": "ProductCategories"
        },
        {
            "Name": "Products",
            "Query": "Products"
        }
    ],
    "_Type": "Action.Type.ODataService.Initialize",
    "ShowActivityIndicator": true,
    "ActivityIndicatorText": "Downloading...",
    "ActionResult": {
        "_Name": "init"
    },
    "OnFailure": "/samplemdk/Actions/mobileappazeem/Service/InitializeOfflineFailureMessage.action"
}