{
    "Message": "Upload in progress...",
    "CompletionMessage": "Sync completed",
    "CompletionTimeout": 7,
    "OnSuccess": "/samplemdk/Actions/mobileappazeem/Service/UploadOffline.action",
    "OnFailure": "/samplemdk/Actions/mobileappazeem/Service/SyncFailureMessage.action",
    "_Type": "Action.Type.ProgressBanner"
}