{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "Dropdown",
        "Service": "/pp/Services/capurl.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "questionnaire_id": "#Control:questionnaire_id/#Value",
        "dropdown_value": "#Control:dropdown_value/#Value"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/pp/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/pp/Actions/UpdateEntityFailureMessage.action"
}