{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "Questionnaire_reply_table",
        "Service": "/pp/Services/capurl.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "doc_id": "#Control:doc_id/#Value",
        "questionnaire_id": "#Control:questionnaire_id/#SelectedValue",
        "invitationId": "#Control:invitationId/#SelectedValue",
        "user_reply": "#Control:user_reply/#Value",
        "description": "#Control:description/#Value",
        "type": "#Control:type/#Value"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/pp/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/pp/Actions/UpdateEntityFailureMessage.action"
}