{
    "_Type": "Action.Type.ODataService.UploadStream",
    "Target": {
        "Service": "/samplemdk/Services/mobileappazeem.service",
        "EntitySet": "Products",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "Picture": "#Control:Picture/#Value"
    },
    "ShowActivityIndicator": true,
    "ActionResult": {
        "_Name": "uploadstream"
    },
    "OnSuccess": "/samplemdk/Actions/UploadStreamSuccessMessage.action",
    "OnFailure": "/samplemdk/Actions/UploadStreamFailureMessage.action"
}