{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/pp/Pages/capurl_Questionnaire_table/Questionnaire_table_CreateQuestionnaire_reply_table.page",
    "_Type": "Action.Type.Navigation"
}