{
    "Message": "Upload in progress...",
    "CompletionMessage": "Sync completed",
    "CompletionTimeout": 7,
    "OnSuccess": "/pp/Actions/capurl/Service/UploadOffline.action",
    "OnFailure": "/pp/Actions/capurl/Service/SyncFailureMessage.action",
    "_Type": "Action.Type.ProgressBanner"
}